version: '2'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        version: "0.0.1"
        environment: beta
    hostname: default
    ports:
    - "8001:3000"
    entrypoint:
    - npm
    - run
    - start
